# Generated by Django 4.1 on 2022-10-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='text_enc',
            field=models.BooleanField(default=0, help_text='投稿内容を16進数化するかどうか'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postmodel',
            name='user',
            field=models.CharField(blank=True, help_text='名無しでもOK', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='user_enc',
            field=models.BooleanField(default=0, help_text='名前を16進数化するかどうか'),
            preserve_default=False,
        ),
    ]
