# Generated by Django 4.1 on 2022-10-20 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_postmodel_text_enc_postmodel_user_postmodel_user_enc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='text_enc',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='user_enc',
        ),
    ]
