# Generated by Django 4.1 on 2022-10-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_postmodel_text_enc_remove_postmodel_user_enc'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='text_enc',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postmodel',
            name='user_enc',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
