# Generated by Django 4.1 on 2022-10-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_postmodel_text_enc_postmodel_user_enc'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='good',
            field=models.IntegerField(default=0, verbose_name='Good'),
        ),
    ]
