# Generated by Django 4.1 on 2023-02-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_postmodel_good'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='user',
            field=models.CharField(blank=True, help_text='名無しでもOK', max_length=30, null=True),
        ),
    ]
